FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_KEY
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]