name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    tags-ignore:
      - '*'

jobs:
  version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN || github.token }}

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY_HML }}
        run: npm run build

      - name: Rodar testes
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Instalar semver
        run: npm install -g semver

      - name: Calcular nova versão
        id: version
        shell: bash
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s")
          VERSION_TYPE="patch"
          
          while IFS= read -r COMMIT; do
            if [[ "$COMMIT" == *"BREAKING CHANGE"* ]]; then VERSION_TYPE="major"; break
            elif [[ "$COMMIT" =~ ^feat(\(.+\))?: ]]; then VERSION_TYPE="minor"
            elif [[ "$COMMIT" =~ ^fix(\(.+\))?: ]]; then [ "$VERSION_TYPE" != "minor" ] && VERSION_TYPE="patch"; fi
          done <<< "$COMMITS"

          NEW_VERSION=$(semver -i $VERSION_TYPE ${LAST_TAG#v})
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Atualizar package.json
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" != "${{ steps.version.outputs.new_version }}" ]; then
            npm version ${{ steps.version.outputs.new_version }} --no-git-tag-version
          else
            echo "Versão $CURRENT_VERSION já definida. Pulando atualização."
          fi

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ env.new_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://achamigos-backend-latest.onrender.com
            NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}

      - name: Commit e controle de tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add package.json package-lock.json
          git commit -m "chore(release): version ${{ env.new_version }} [skip ci]" || echo "Sem mudanças"
          git push origin HEAD:${{ github.ref_name }}

          BRANCH_NAME="${{ github.ref_name }}"
          TAG_NAME=$([ "$BRANCH_NAME" = "main" ] && echo "v${{ env.new_version }}" || echo "v${{ env.new_version }}-beta")
          
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Trigger Render Deploy (Front-End)
        run: |
          # Deploy sempre no Front de Homologação (develop/main)
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONT_HML }}"
          
          # Se for a main, deploy também no Front de Produção
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Deployando Front em PRODUÇÃO..."
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONT_PROD }}"
          fi

      - name: Deploy para Heroku (Container)
        if: github.ref == 'refs/heads/main'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          
          heroku container:login
          
          cp Dockerfile.heroku Dockerfile
          
          heroku container:push web -a achamigos-backend-prod
          heroku container:release web -a achamigos-backend-prod 

      - name: Enviar email se falhar
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Falha no pipeline - ${{ github.repository }}
          body: O pipeline do GitHub Actions falhou na versão ${{ env.new_version }}.
          to: ${{ secrets.EMAIL_USER }}
          from: GitHub Actions