name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    tags-ignore:
      - '*'

jobs:
  version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      - name: Rodar testes
        run: npm test


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (Validação)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          
          tags: front-end:test
    

      - name: Incrementar versão automaticamente
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version | sed 's/^v//')
          echo "Nova versão: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

              
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Verificar/Cria repositório no Docker Hub
        run: |
          REPO="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"

          echo "Verificando se repositório existe: $REPO"

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
            https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}/)

          if [ "$STATUS" = "200" ]; then
            echo "Repositório já existe 👍"
          else
            echo "Repositório não existe. Criando..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
              -d "{\"name\": \"${{ secrets.DOCKERHUB_REPO }}\", \"is_private\": false}" \
              https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/
            echo "Repositório criado com sucesso!"
          fi

   
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true

          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ env.new_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest


      - name: Commit e controle de tags
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add package.json package-lock.json
          git commit -m "chore(release): version $new_version [skip ci]" || echo "Sem mudanças"

          BRANCH_NAME="${{ github.ref_name }}"

          # Sempre envia o commit
          git push origin HEAD:${{ github.ref_name }}

          # 🔥 Controle de tags
          if [ "$BRANCH_NAME" = "main" ]; then
            TAG_NAME="v$new_version"

          elif [ "$BRANCH_NAME" = "develop" ]; then
            TAG_NAME="v$new_version-beta"

          else
            echo "Branch $BRANCH_NAME não gera tag"
            exit 0
          fi

          # Evita erro se a tag já existir
          if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi

      - name: Enviar email se falhar
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Falha no pipeline - ${{ github.repository }}
          body: O pipeline do GitHub Actions falhou.
          to: ${{ secrets.EMAIL_USER }}
          from: GitHub Actions